In [74]:
import pandas as pd
import numpy as np

In [75]:
pd.set_option('display.max_rows',None) 
pd.set_option('display.max_columns',None)

In [76]:
df = pd.read_csv('gurgaon_properties.csv')

In [77]:
df.head(2)

,property_name,property_type,society,price,sector,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,area_sqft
0,3 Bedroom House for sale in Sector 33 Gurgaon,house,nitin vihar,0.85,NaN,9444.0,Plot area 900(83.61 sq.m.),3,2,0,not available,"Sector 33 Gurgaon, Gurgaon, Haryana",1.0,West,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Airforce Hospital', 'S...",Independent house available for sale in nitin ...,NaN,"['High Ceiling Height', 'Water Storage', 'No o...","['Environment3 out of 5', 'Lifestyle4 out of 5...",900.0
1,2 BHK Flat in Ashok Vihar Phase 2,flat,shyam sadan,0.55,ashok vihar phase 2,6470.0,Carpet area: 700 (65.03 sq.m.),2,2,1,study room,"Ashok Vihar Phase 2, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Sheetla Mata Mandir', 'Chintapurni Mandir', ...",One of the best locations in gurugram as gurga...,"['2 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Security / Fire Alarm', 'Lift(s)', 'Water pu...","['Environment3 out of 5', 'Safety4 out of 5', ...",850.0

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   sector           2997 non-null   object
 5   price_per_sqft   3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  noOfFloor        3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
 20  area_sqft        3941 non-null   float64
dtypes: float64(4), int64(2), object(15)
memory usage: 650.0+ KB

In [79]:
df.drop(columns = 'sector',inplace=True)

In [80]:
df.shape

(3961, 20)

In [81]:
df.isna().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
noOfFloor            21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
area_sqft            20
dtype: int64

In [82]:
df.duplicated().sum()

np.int64(0)

In [83]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [84]:
df.head(2)

,property_name,property_type,society,sector,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,area_sqft
0,3 Bedroom House for sale in Sector 33 Gurgaon,house,nitin vihar,Sector 33,0.85,9444.0,Plot area 900(83.61 sq.m.),3,2,0,not available,"Sector 33 Gurgaon, Gurgaon, Haryana",1.0,West,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Airforce Hospital', 'S...",Independent house available for sale in nitin ...,NaN,"['High Ceiling Height', 'Water Storage', 'No o...","['Environment3 out of 5', 'Lifestyle4 out of 5...",900.0
1,2 BHK Flat in Ashok Vihar Phase 2,flat,shyam sadan,Ashok Vihar Phase 2,0.55,6470.0,Carpet area: 700 (65.03 sq.m.),2,2,1,study room,"Ashok Vihar Phase 2, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Sheetla Mata Mandir', 'Chintapurni Mandir', ...",One of the best locations in gurugram as gurga...,"['2 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Security / Fire Alarm', 'Lift(s)', 'Water pu...","['Environment3 out of 5', 'Safety4 out of 5', ...",850.0

In [85]:
df['sector'].isna().sum()

np.int64(0)

In [86]:
df['sector']=df['sector'].str.lower()

In [ ]:
df['sector'].value_counts()

In [88]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [89]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [90]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [91]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [92]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [93]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [94]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [95]:
a = df['sector'].value_counts()[df['sector'].value_counts()>=3]

In [96]:
df = df[df['sector'].isin(a.index)]

In [ ]:
df['sector'].value_counts()

In [98]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [99]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [100]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,area_sqft
230,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN,1776.0
3444,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN,690.0
3452,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN,3500.0
3676,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN,1200.0

In [101]:
df.loc[230,'sector'] = 'sector 81'
df.loc[3444,'sector'] = 'sector 81'
df.loc[3452,'sector'] = 'sector 81'
df.loc[3676,'sector'] = 'sector 81'

In [ ]:
df['sector'].value_counts()

In [103]:
df['sector'] = df['sector'].str.replace('sector 99a','sector 99')
df['sector'] = df['sector'].str.replace('sector 88a','sector 88')
df['sector'] = df['sector'].str.replace('sector 67a','sector 67')
df['sector'] = df['sector'].str.replace('sector 82a','sector 82')
df['sector'] = df['sector'].str.replace('sector 63a','sector 63')
df['sector'] = df['sector'].str.replace('sector 82a','sector 82')
df['sector'] = df['sector'].str.replace('sector 36a','sector 36')
df['sector'] = df['sector'].str.replace('sector 9a','sector 9')
df['sector'] = df['sector'].str.replace('sector 10a','sector 10')
df['sector'] = df['sector'].str.replace('sector 17b','sector 17')
df['sector'] = df['sector'].str.replace('sector 88b','sector 88')

In [104]:
df['sector'] = df['sector'].str.replace('sector 17a','sector 17')
df['sector'] = df['sector'].str.replace('sector 9b','sector 9')
df['sector'] = df['sector'].str.replace('sector-5 sohna','sector 5')
df['sector'] = df['sector'].str.replace('sector 12 near sadar bazar','sector 12')
df['sector'] = df['sector'].str.replace('part 3 sector 5','sector 5')
df['sector'] = df['sector'].str.replace('urban estate, sector 5','sector 5')
df['sector'] = df['sector'].str.replace('sector-35 sohna','sector 35')
df['sector'] = df['sector'].str.replace('block h sector 3 phase iii extension','sector 3')

In [105]:
df['sector'] = df['sector'].str.replace('sector 50 pocket h','sector 50')
df['sector'] = df['sector'].str.replace('sector-5 sheetla colony','sector 5')
df['sector'] = df['sector'].str.replace('sector-7 hous','sector 7')
df['sector'] = df['sector'].str.replace('sector 17c','sector 17')
df['sector'] = df['sector'].str.replace('new sector 7','sector 7')
df['sector'] = df['sector'].str.replace('sector 21a faridabad ','sector 21')
df['sector'] = df['sector'].str.replace('sector 37a','sector 37')
df['sector'] = df['sector'].str.replace('sector 21a faridabad','sector 21')
df['sector'] = df['sector'].str.replace('v block sector 24','sector 24')

In [106]:
df['sector'].shape

(3803,)

In [107]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,area_sqft
1042,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",500.0
1602,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5...",270.0
1777,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",1137.0
3070,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ...",884.0
3718,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",594.0

In [108]:
df.loc[[1042,1602,1777,3070,3718],'sector'] = 'sector 110'

In [109]:
df.shape

(3803, 21)

In [111]:
df.duplicated().sum()

np.int64(0)

In [112]:
df1 = df.copy()

In [114]:
df1.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [115]:
df1.shape

(3803, 17)

In [116]:
df1.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)